development:
  adapter: mysql2
  encoding: utf8
  database: runners_shikaku_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: runners_shikaku_test
  pool: 5
  username: root
  password:

production:
  adapter: pg
  encoding: utf-8
  database: runners_shikaku_production
  pool: 5
  username: root
  password:
